fix: use $effect callback to destroy the component instead of onDestroy.
This also fix the issue on Inertia SSR.
Error message:

ReferenceError: document is not defined
    at file:///Users/kresnasatya/Projects/svelte-laravel/bootstrap/ssr/assets/DeleteUserForm-tJuLmpWq.js:42:5